// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.3.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#ifdef __cpp_constexpr
#define __pio_const constexpr
#else
#define __pio_const const
#endif

// ---------- //
// serialboot //
// ---------- //

#define serialboot_wrap_target 0
#define serialboot_wrap 3
#define serialboot_pio_version 0

static __pio_const uint16_t serialboot_program_instructions[] = {
            //     .wrap_target
    0xe901, //  0: set    pins, 1                [9]
    0xa025, //  1: mov    x, status
    0x0024, //  2: jmp    !x, 4
    0xeb00, //  3: set    pins, 0                [11]
            //     .wrap
    0xe000, //  4: set    pins, 0
    0x6020, //  5: out    x, 32
    0xf55c, //  6: set    y, 28                  [21]
    0xf701, //  7: set    pins, 1                [23]
    0xf700, //  8: set    pins, 0                [23]
    0xf601, //  9: set    pins, 1                [22]
    0x0088, // 10: jmp    y--, 8
    0x6001, // 11: out    pins, 1
    0x004b, // 12: jmp    x--, 11
    0xc000, // 13: irq    nowait 0
    0x0000, // 14: jmp    0
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program serialboot_program = {
    .instructions = serialboot_program_instructions,
    .length = 15,
    .origin = -1,
    .pio_version = serialboot_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config serialboot_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + serialboot_wrap_target, offset + serialboot_wrap);
    return c;
}
#endif

